base: 
  project: Metro-Interstate-Traffic_Analysis
  random_state: 42
  target_col : traffic_volume

data_source: 
  source_data: data_given/Metro_Interstate_Traffic_Volume.csv

load_data:
  raw_dataset_csv: data/raw/traffic_data.csv

validate_data:
  schema: 
    columns: 
      holiday: object
      temp: float64
      rain_1h: float64
      snow_1h: float64
      clouds_all: int64
      weather_main: object
      weather_description: object
      date_time: object
      traffic_volume: int64
    
    no_of_rows: 48204

    no_of_cols: 9 

prepare_data:
  cleaned_data_path: data/prepared/cleaned_traffic_data.csv
  model_data_path: data/prepared/model_traffic_data.csv

split_data:
  train_path: data/processed/train_traffic_data.csv
  test_path: data/processed/test_traffic_data.csv
  test_size: 0.20 

train_evaluate:
  estimators:
    XGBoostRegressor: 
      params:
        alpha: 0.5
        cosample_bytree: 1
        max_depth: 9
        min_child_weight: 1
        subsample: 1
        # alpha: 0.5
        # cosample_bytree: 1
        # max_depth: 10
        # min_child_weight: 4
        # subsample: 0

  prediction_model_path: prediction_service/model

  model_reports: model_reports

  reports:
    scores_file : model_reports/scores.json
    params_file : model_reports/params.json

production_model_path: saved_models/model.joblib

web_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: XGBoostRegressor
  run_name: mlops
  registered_model_name: XGBR_TRAFFIC_MODEL
  remote_server_uri: http://127.0.0.1:1234


